name: "Terraform"

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
      - name: generate-tfvars
        run: |
          echo "name = \"${{ github.repository_owner }}\"" > terraform.tfvars
      - run: terraform init
      - run: terraofrm plan
      - run: terraform apply -auto-approve
